#apiVersion: kustomize.toolkit.fluxcd.io/v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kbot
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: kbot
    namespace: flux-system
  targetNamespace: demo
  timeout: 2m
