apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kbot
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/dev/kbot
  prune: true
  sourceRef:
    kind: GitRepository
    name: kbot       # 👈 має збігатися з назвою `GitRepository`!
    namespace: flux-system
  targetNamespace: default
  timeout: 2m
