apiVersion: v1
kind: Service
metadata:
  name: {{ include "kbot-1.0.13.tgz.fullname" . }}
  labels:
    {{- include "kbot-1.0.13.tgz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kbot-1.0.13.tgz.selectorLabels" . | nindent 4 }}
