# clusters/dev/kbot/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kbot
  namespace: default
spec:
  releaseName: kbot
  interval: 1m
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: kbot
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/tenariaz/kbot
      tag: "latest"  # буде оновлено через GitHub Actions
